
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: wanconfigurations.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: WanConfiguration
    listKind: WanConfigurationList
    plural: wanconfigurations
    singular: wanconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: WanConfiguration is the Schema for the wanconfigurations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WanConfigurationSpec defines the desired state of WanConfiguration
            properties:
              acknowledgement:
                description: Acknowledgement is the configuration for the condition
                  when the next batch of WAN events are sent.
                properties:
                  timeout:
                    default: 60000
                    description: Timeout represents the time the source cluster waits
                      for the acknowledgement. After timeout, the events will be resent.
                    format: int32
                    type: integer
                  type:
                    default: ACK_ON_OPERATION_COMPLETE
                    description: Type represents how a batch of replication events
                      is considered successfully replicated.
                    enum:
                    - ACK_ON_OPERATION_COMPLETE
                    - ACK_ON_RECEIPT
                    type: string
                type: object
              batch:
                description: Batch is the configuration for WAN events batch.
                properties:
                  maximumDelay:
                    default: 1000
                    description: MaximumDelay represents the maximum delay in milliseconds.
                      If the batch size is not reached, the events will be sent after
                      the maximum delay.
                    format: int32
                    type: integer
                  size:
                    default: 500
                    description: Size represents the maximum batch size.
                    format: int32
                    type: integer
                type: object
              endpoints:
                description: Endpoints is the target cluster endpoints.
                minLength: 1
                type: string
              mapResourceName:
                description: MapResourceName is the name of Map custom resource which
                  WAN replication will be applied to.
                minLength: 1
                type: string
              queue:
                description: Queue is the configuration for WAN events queue.
                properties:
                  capacity:
                    default: 10000
                    description: Capacity is the total capacity of WAN queue.
                    format: int32
                    type: integer
                  fullBehavior:
                    default: DISCARD_AFTER_MUTATION
                    description: FullBehavior represents the behavior of the new arrival
                      when the queue is full.
                    enum:
                    - DISCARD_AFTER_MUTATION
                    - THROW_EXCEPTION
                    - THROW_EXCEPTION_ONLY_IF_REPLICATION_ACTIVE
                    type: string
                type: object
              targetClusterName:
                description: ClusterName is the clusterName field of the target Hazelcast
                  resource.
                minLength: 1
                type: string
            required:
            - endpoints
            - mapResourceName
            - targetClusterName
            type: object
          status:
            description: WanConfigurationStatus defines the observed state of WanConfiguration
            properties:
              state:
                description: State represents the current Hazelcast WAN Replication
                  state
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
